### ISSUE TITLE
Consider ad this to elpa

### ISSUE THREAD

**Issue by Ergus** [Fanael/highlight-numbers#16]
Hi @Fanael:

Have you considered to add this package to elpa? It is simple and useful enough to do so. Could you consider to do that?

**Comment by Fanael** [comment]
GNU ELPA is a non-free repository because it requires you to sign a CLA that gives the ownership to the FSF to submit your package there, thus violating one of the basic freedoms of free software that the FSF conveniently omits, namely the freedom to contribute upstream, because people who'd want to contribute would need to sign the CLA too. I'm afraid it's not possible for me to do that unless the FSF changes their ways.

**Comment by npostavs** [comment]
I'm not trying to change your mind about adding this package to GNU ELPA, but I couldn't let this pass by:

> the freedom to contribute upstream

There is always the freedom to contribute (just send an email or whatever), but upstream isn't obligated to accept contributions. I guess what you mean is that upstream should only be able to reject contributions for technical reasons. However, that's not a freedom, but a restriction (on upstream).

Anyway, refusing to put your package in GNU ELPA because you don't like how the FSF manages its repositories is entirely legitimate; as I said at the top, I'm not trying to argue against that part of it.

**Comment by Fanael** [comment]
> There is always the freedom to contribute (just send an email or whatever)

No, there isn't, the FSF decided that only the FSF can contribute. That's the entire reason they have the CLA process: so that the entirety of copyright belongs to the FSF.

> I guess what you mean is that upstream should only be able to reject contributions for technical reasons.

Yes, that's a given. I'm fine with patches being rejected because they're buggy or out of scope or whatever other technical reason there might be, I'm not fine with patches being rejected because the upstream doesn't own them or other bullshit "intellectual" "property" "law" reasons.

> However, that's not a freedom, but a restriction (on upstream).

Let's just agree to disagree, just like the FSF wants a world where everyone can do whatever they want with the software they got, including use, modification and redistribution, I want a world where everyone can do that *and* contribute upstream, to prevent unnecessary duplication of work and fragmentation resulting from there being hundred billion forks. And just like them, I'm not willing to compromise on my ideals.

**Comment by cpitclaudel** [comment]
> That's the entire reason they have the CLA process: so that the entirety of copyright belongs to the FSF.

Is that true? AFAIU, Emacs *will* take public domain patches if you send them.  See https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

Have you considered this option?

**Comment by Fanael** [comment]
Very few countries actually allow you to give up all copyright claims, thus making your work available under public domain; as far as I know, the United States of Drone Striking Innocent Civilians is the only state where this notion is known to work. Since I don't live there, nor have any desire to move there whatsoever, that's not an option for me.

**Comment by cpitclaudel** [comment]
Hm. Doesn't CC0 work worldwide?

**Comment by Fanael** [comment]
That's just a fallback copyright license, I doubt the FSF will accept it because it doesn't make them the sole copyright owner.
